project:
  type: website
  output-dir: docs

website:
  title: "Tech Guides"
  sidebar:
    style: "floating"
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  
editor: visual

